[workspace]
members = [
  "crates/pyagent",
  "crates/builder_derive",
  "crates/core",
  "crates/jvm_core",
  "crates/jvm_sdk_agent",
  "crates/jvm_bare_agent",
  "crates/wasm",
  "crates/node",
]

[profile.release]
panic = "abort"
